name: TryHackMe Badge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve badge
        run: |
          curl -o tryhackme-badge.png https://tryhackme.com/p/ItzHerbie
      - name: Add badge to README
        run: |
          echo "![](tryhackme-badge.png)" >> README.md
